export const GAME_EVENTS = {
  QUEST_ACCEPTED: "QUEST_ACCEPTED",
  QUEST_COMPLETED: "QUEST_COMPLETED",
  QUEST_FAILED: "QUEST_FAILED",
  XP_GAINED: "XP_GAINED",
  LEVEL_UP: "LEVEL_UP",
  RANK_UP: "RANK_UP",
  PENALTY_TRIGGERED: "PENALTY_TRIGGERED",
  DUNGEON_ENTERED: "DUNGEON_ENTERED",
  DUNGEON_COMPLETED: "DUNGEON_COMPLETED",
  DUNGEON_FAILED: "DUNGEON_FAILED",
  ENCOUNTER_STARTED: "ENCOUNTER_STARTED",
  ENCOUNTER_COMPLETED: "ENCOUNTER_COMPLETED",
  ENCOUNTER_ANSWER_CORRECT: "ENCOUNTER_ANSWER_CORRECT",
  ENCOUNTER_ANSWER_WRONG: "ENCOUNTER_ANSWER_WRONG",
  SPEECH_RECORDED: "SPEECH_RECORDED",
  SPEECH_ANALYZED: "SPEECH_ANALYZED",
  AI_RESPONSE_GENERATED: "AI_RESPONSE_GENERATED",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  SAVE_TRIGGERED: "SAVE_TRIGGERED",
  AUTOSAVE_COMPLETED: "AUTOSAVE_COMPLETED",
  VOCABULARY_MASTERED: "VOCABULARY_MASTERED",
  VOCABULARY_PREPARATION_READY: "VOCABULARY_PREPARATION_READY",
  UNLOCK_GRANTED: "UNLOCK_GRANTED",
} as const

export type GameEventType =
  (typeof GAME_EVENTS)[keyof typeof GAME_EVENTS]
