export const GAME_EVENTS = {
  QUEST_ACCEPTED: "QUEST_ACCEPTED",
  QUEST_COMPLETED: "QUEST_COMPLETED",
  QUEST_FAILED: "QUEST_FAILED",
  XP_GAINED: "XP_GAINED",
  LEVEL_UP: "LEVEL_UP",
  RANK_UP: "RANK_UP",
  PENALTY_TRIGGERED: "PENALTY_TRIGGERED",
  DUNGEON_ENTERED: "DUNGEON_ENTERED",
  DUNGEON_COMPLETED: "DUNGEON_COMPLETED",
  SPEECH_ANALYZED: "SPEECH_ANALYZED",
  AI_RESPONSE_GENERATED: "AI_RESPONSE_GENERATED",
  SAVE_TRIGGERED: "SAVE_TRIGGERED",
  AUTOSAVE_COMPLETED: "AUTOSAVE_COMPLETED",
} as const

export type GameEventType =
  (typeof GAME_EVENTS)[keyof typeof GAME_EVENTS]
