export const READINESS_CONFIG = {
  CORRUPTION_PENALTY_PER_POINT: 2,
  FATIGUE_PENALTY_PER_POINT: 1.5,
  XP_DEBT_PENALTY_DIVISOR: 10,
  XP_DEBT_PENALTY_CAP: 15,
  LISTENING_BONUS_PER_POINT: 0.25,
  LISTENING_BONUS_CAP: 12,
  SURVIVAL_THRESHOLDS: {
    CRITICAL: 35,
    UNSTABLE: 55,
    STABLE: 75,
  },
} as const
