/**
 * Build src/data/jmdictCurated.generated.ts from JMdict XML + content manifest.
 *
 * Usage:
 *   npm run build:curated -- <path-to-JMdict_e.xml>
 *   npm run build:curated -- --download   (fetch JMdict_e.gz into data/)
 */
import {
  createWriteStream,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  createReadStream,
} from "fs"
import { createGunzip } from "zlib"
import { get as httpGet } from "http"
import { get as httpsGet } from "https"
import { pipeline } from "stream/promises"
import { resolve } from "path"
import { parseJmdictXml } from "../src/services/jmdict/parser"
import { normalizeJapanese, toVocabularyEntry } from "../src/services/jmdict/normalize"
import type { VocabularyEntryContract } from "../contracts/vocabulary-contract"
import { JMDICT_FREQUENCY_TIERS } from "../src/config/jmdictConfig"

const JMDICT_GZ_URL = "https://ftp.edrdg.org/pub/Nihongo/JMdict_e.gz"
const MANIFEST_PATH = resolve(process.cwd(), "content/jmdict-curated-manifest.json")
const OUTPUT_PATH = resolve(process.cwd(), "src/data/jmdictCurated.generated.ts")
const DATA_DIR = resolve(process.cwd(), "data")
const DEFAULT_XML = resolve(DATA_DIR, "JMdict_e.xml")

type TierName = keyof typeof JMDICT_FREQUENCY_TIERS

interface ManifestRow {
  japanese: string
  reading?: string
  romaji?: string
  meanings?: string[]
  jlpt?: string
  tier?: TierName
}

interface ManifestFile {
  entries: ManifestRow[]
}

function tierValue(name: TierName | undefined): number {
  if (!name) return JMDICT_FREQUENCY_TIERS.UNKNOWN
  return JMDICT_FREQUENCY_TIERS[name] ?? JMDICT_FREQUENCY_TIERS.UNKNOWN
}

function buildLookup(entries: VocabularyEntryContract[]) {
  const byKanji = new Map<string, VocabularyEntryContract[]>()
  const byReading = new Map<string, VocabularyEntryContract[]>()

  for (const entry of entries) {
    for (const k of entry.japanese) {
      const key = normalizeJapanese(k)
      const list = byKanji.get(key) ?? []
      list.push(entry)
      byKanji.set(key, list)
    }
    for (const r of entry.reading) {
      const key = normalizeJapanese(r)
      const list = byReading.get(key) ?? []
      list.push(entry)
      byReading.set(key, list)
    }
  }

  return { byKanji, byReading }
}

function scoreMatch(
  entry: VocabularyEntryContract,
  row: ManifestRow
): number {
  const key = normalizeJapanese(row.japanese)
  let score = 0
  if (entry.japanese.some((k) => normalizeJapanese(k) === key)) {
    score += 100
  } else if (
    entry.japanese.some((k) => normalizeJapanese(k).includes(key))
  ) {
    score += 25
  } else {
    score -= 80
  }

  if (row.reading) {
    const r = normalizeJapanese(row.reading)
    if (entry.reading.some((reb) => normalizeJapanese(reb) === r)) {
      score += 90
    } else {
      score -= 40
    }
  }

  return score - entry.frequencyTier * 0.01
}

function lookupEntry(
  lookup: ReturnType<typeof buildLookup>,
  row: ManifestRow
): VocabularyEntryContract | undefined {
  const key = normalizeJapanese(row.japanese)
  const seen = new Map<number, VocabularyEntryContract>()

  for (const entry of lookup.byKanji.get(key) ?? []) {
    seen.set(entry.entSeq, entry)
  }
  if (row.reading) {
    for (const entry of lookup.byReading.get(normalizeJapanese(row.reading)) ?? []) {
      seen.set(entry.entSeq, entry)
    }
  }
  for (const entry of lookup.byReading.get(key) ?? []) {
    seen.set(entry.entSeq, entry)
  }

  const candidates = [...seen.values()]
  if (!candidates.length) return undefined

  const ranked = candidates
    .map((entry) => ({ entry, score: scoreMatch(entry, row) }))
    .sort((a, b) => b.score - a.score)

  const best = ranked[0]
  if (!best || best.score < 60) return undefined
  return best.entry
}

function assertResolvedMatch(
  row: ManifestRow,
  entry: VocabularyEntryContract
): void {
  const key = normalizeJapanese(row.japanese)
  const kanjiOk = entry.japanese.some((k) => normalizeJapanese(k) === key)
  if (kanjiOk) return
  if (row.reading) {
    const r = normalizeJapanese(row.reading)
    const readingOk = entry.reading.some((reb) => normalizeJapanese(reb) === r)
    if (readingOk) return
  }
  throw new Error(
    `Manifest "${row.japanese}" resolved to "${entry.japanese[0]}" (ent_seq ${entry.entSeq})`
  )
}

function escapeString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')
}

function emitGeneratedFile(
  rows: ManifestRow[],
  resolved: VocabularyEntryContract[]
): void {
  const lines: string[] = [
    "/** AUTO-GENERATED by scripts/extract-jmdict-curated.ts — do not edit by hand. */",
    'import type { VocabularyEntryContract } from "@/contracts/vocabulary-contract"',
    'import { JMDICT_FREQUENCY_TIERS } from "@/config/jmdictConfig"',
    'import { toVocabularyEntry } from "@/services/jmdict/normalize"',
    "",
    "const CURATED_RAW: Array<{",
    "  entSeq: number",
    "  japanese: string",
    "  reading: string",
    "  romaji?: string",
    "  meanings: string[]",
    "  jlpt: string",
    "  frequencyTier: number",
    "}> = [",
  ]

  for (let i = 0; i < rows.length; i++) {
    const row = rows[i]!
    const entry = resolved[i]!
    const japanese = entry.japanese[0] ?? row.japanese
    const reading =
      row.reading ??
      entry.reading.find((r) => /[\u3040-\u309f]/.test(r)) ??
      entry.reading[0] ??
      ""
    const meanings = row.meanings ?? entry.meanings.slice(0, 4)
    const jlpt = row.jlpt ?? entry.jlpt ?? "N3"
    const frequencyTier = row.tier ? tierValue(row.tier) : entry.frequencyTier
    const tierKey =
      row.tier ??
      (Object.entries(JMDICT_FREQUENCY_TIERS).find(
        ([, v]) => v === frequencyTier
      )?.[0] as TierName | undefined)

    lines.push("  {")
    lines.push(`    entSeq: ${entry.entSeq},`)
    lines.push(`    japanese: "${escapeString(japanese)}",`)
    lines.push(`    reading: "${escapeString(reading)}",`)
    if (row.romaji) {
      lines.push(`    romaji: "${escapeString(row.romaji)}",`)
    }
    lines.push(
      `    meanings: [${meanings.map((m) => `"${escapeString(m)}"`).join(", ")}],`
    )
    lines.push(`    jlpt: "${jlpt}",`)
    if (tierKey && tierKey in JMDICT_FREQUENCY_TIERS) {
      lines.push(`    frequencyTier: JMDICT_FREQUENCY_TIERS.${tierKey},`)
    } else {
      lines.push(`    frequencyTier: ${frequencyTier},`)
    }
    lines.push("  },")
  }

  lines.push("]")
  lines.push("")
  lines.push(
    "export const JMDICT_CURATED_GENERATED: VocabularyEntryContract[] = CURATED_RAW.map((row) =>"
  )
  lines.push("  toVocabularyEntry({")
  lines.push("    entSeq: row.entSeq,")
  lines.push("    japanese: [row.japanese],")
  lines.push("    reading: [row.reading],")
  lines.push("    meanings: row.meanings,")
  lines.push("    jlpt: row.jlpt,")
  lines.push("    frequencyTier: row.frequencyTier,")
  lines.push("    romaji: row.romaji,")
  lines.push("  })")
  lines.push(")")
  lines.push("")

  writeFileSync(OUTPUT_PATH, lines.join("\n"), "utf-8")
}

async function downloadJmdict(): Promise<string> {
  const gzPath = resolve(DATA_DIR, "JMdict_e.gz")
  const xmlPath = DEFAULT_XML

  if (!existsSync(DATA_DIR)) {
    mkdirSync(DATA_DIR, { recursive: true })
  }

  if (existsSync(xmlPath)) {
    console.log(`Using existing ${xmlPath}`)
    return xmlPath
  }

  if (!existsSync(gzPath)) {
    console.log(`Downloading ${JMDICT_GZ_URL} ...`)
    await new Promise<void>((resolveDl, reject) => {
      const file = createWriteStream(gzPath)
      const request = (url: string) => {
        const fetch = url.startsWith("https:") ? httpsGet : httpGet
        fetch(url, (res) => {
          if (
            res.statusCode &&
            res.statusCode >= 300 &&
            res.statusCode < 400 &&
            res.headers.location
          ) {
            request(res.headers.location)
            return
          }
          if (res.statusCode !== 200) {
            reject(new Error(`Download failed: HTTP ${res.statusCode}`))
            return
          }
          res.pipe(file)
          file.on("finish", () => resolveDl())
        }).on("error", reject)
      }
      request(JMDICT_GZ_URL)
    })
    console.log(`Saved ${gzPath}`)
  }

  console.log(`Decompressing to ${xmlPath} ...`)
  await pipeline(
    createReadStream(gzPath),
    createGunzip(),
    createWriteStream(xmlPath)
  )
  return xmlPath
}

async function main(): Promise<void> {
  const arg = process.argv[2]
  let xmlPath: string

  if (arg === "--download" || arg === "-d") {
    xmlPath = await downloadJmdict()
  } else if (arg) {
    xmlPath = resolve(arg)
  } else if (existsSync(DEFAULT_XML)) {
    xmlPath = DEFAULT_XML
  } else {
    console.log("Usage: npm run build:curated -- <path-to-JMdict_e.xml>")
    console.log("       npm run build:curated -- --download")
    process.exit(1)
  }

  if (!existsSync(xmlPath)) {
    console.error(`File not found: ${xmlPath}`)
    process.exit(1)
  }

  if (!existsSync(MANIFEST_PATH)) {
    console.error(`Manifest not found: ${MANIFEST_PATH}`)
    process.exit(1)
  }

  const manifest = JSON.parse(
    readFileSync(MANIFEST_PATH, "utf-8")
  ) as ManifestFile

  console.log(`Parsing ${xmlPath} ...`)
  const xml = readFileSync(xmlPath, "utf-8")
  const allEntries = parseJmdictXml(xml)
  console.log(`Indexed ${allEntries.length} JMdict entries.`)

  const lookup = buildLookup(allEntries)
  const resolved: VocabularyEntryContract[] = []
  const missing: string[] = []

  for (const row of manifest.entries) {
    const found = lookupEntry(lookup, row)
    if (!found) {
      if (row.reading && row.meanings?.length) {
        resolved.push(
          toVocabularyEntry({
            entSeq: 900_000_000 + resolved.length,
            japanese: [row.japanese],
            reading: [row.reading],
            meanings: row.meanings,
            jlpt: row.jlpt,
            frequencyTier: tierValue(row.tier),
            romaji: row.romaji,
          })
        )
        missing.push(`${row.japanese} (manual fallback)`)
        continue
      }
      missing.push(row.japanese)
      continue
    }
    assertResolvedMatch(row, found)
    resolved.push(found)
  }

  if (missing.some((m) => !m.includes("manual fallback"))) {
    console.error("Unresolved manifest entries:", missing.join(", "))
    process.exit(1)
  }

  if (resolved.length !== manifest.entries.length) {
    console.error(
      `Resolved ${resolved.length} / ${manifest.entries.length} — aborting.`
    )
    process.exit(1)
  }

  emitGeneratedFile(manifest.entries, resolved)
  console.log(`Wrote ${OUTPUT_PATH} (${resolved.length} entries).`)
  if (missing.length) {
    console.warn("Fallbacks:", missing.join(", "))
  }
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
